experiment_dir: NA
logging_dir: NA
n_forward_steps: 5
forward_steps_in_memory: 1
checkpoint_path: /network/group/aopp/predict/HMC005_ANTONIO_EERIE/ace2_data/ace2_era5_ckpt.tar
logging:
  log_to_screen: true
  log_to_wandb: false
  log_to_file: true
  project: ace
stepper_override: 
  ocean:
    surface_temperature_name: surface_temperature
    ocean_fraction_name: ocean_fraction
    interpolate: False # Oean fraction is a bit strange, so I don't trust interpolation at the moment
initial_condition:
  path: /network/group/aopp/predict/HMC005_ANTONIO_EERIE/ace2_data/initial_conditions/ic_2020.nc
  start_indices:
    times:
      - "2020-01-01T00:00:00"
forcing_loader:
  dataset:
    data_path: /network/group/aopp/predict/HMC005_ANTONIO_EERIE/ace2_data/forcing_data
  num_data_workers: 2
  perturbations:
    perturbation_list: []
data_writer:
  save_prediction_files: true
  save_monthly_files: false
  names: ["surface_temperature", "sea_ice_fraction", "TMP2m"]
